--- 
kind: pipeline
type: docker
name: default
steps: 
  - 
    image: plugins/docker
    name: publish
    settings: 
      password: 
        from-secret: docker_password
      repo: cyl07/bot-discord
      username: 
        from-secret: docker_username
    when: 
      branch: master
      event: push