---
kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  commands:
  settings:
  	repo: Cyl/bot-discord
    username:
    	from-secret: docker_username
    password:
    	from-secret: docker_password
  when:
  	branch: master
    event: push

- name: deploy
  image: bot-discord